name: CI

on: [push, pull_request]

jobs:
  java:
    name: Java 1.8
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-java@v1
        with:
          java-version: 1.8
      - name: Build
        run: |
          mvn -B --no-transfer-progress -f p2deps/pom.xml package
          mvn -B --no-transfer-progress -DskipTests package
